# --------------------------------
# Geyser 配置文件
#
# 用于连接《我的世界》基岩版和Java版的桥梁工具。
#
# GitHub：https://github.com/GeyserMC/Geyser
# Discord：https://discord.gg/geysermc
# 维基：https://wiki.geysermc.org/
#
# 注意：请参考 https://wiki.geysermc.org/geyser/setup/ 获取设置指南。许多视频教程已过时。
# 在大多数情况下，尤其是使用服务器托管服务时，需要进行特定于托管平台的额外配置。
# --------------------------------

bedrock:
  # 用于监听连接的IP地址。
  # 通常，只有当你想限制可连接服务器的IP时，才需要取消注释并修改此项。
  #address: 0.0.0.0
  # 用于监听连接的端口
  port: 19132
  # 某些托管服务会在你每次启动服务器时更改Java版端口，并且要求基岩版使用相同的端口。
  # 此选项会使基岩版端口在每次启动服务器时与Java版端口保持一致。
  # 此选项仅适用于插件版本。
  clone-remote-port: false
  # 向《我的世界》基岩版客户端广播的服务器状态信息（MOTD）。如果“passthrough-motd”设为true，则此项无效。
  # 若以下两项为空，对应的内容将默认显示为“Geyser”
  motd1: "Geyser"
  motd2: "另一台Geyser服务器。"
  # 发送给基岩版客户端的服务器名称，在暂停菜单和设置菜单中可见。
  server-name: "Geyser"
  # 对发送给基岩版客户端的网络流量的压缩程度。数值越高，CPU占用越多，但
  # 带宽使用越少。数值低于-1或高于9时无效。设为-1则禁用压缩。
  compression-level: 6
  # 用于向基岩版客户端广播MOTD时指定的连接端口。
  # 除非Geyser的内部运行端口与客户端实际连接端口不同，否则不要取消注释并修改此项。
  # broadcast-port: 19132
  # 是否为客户端启用PROXY协议。除非在Geyser实例前运行UDP反向代理，
  # 否则不需要启用此功能。
  enable-proxy-protocol: false
  # 允许使用PROXY协议的代理IP地址/子网列表。仅当“enable-proxy-protocol”启用时有效，
  # 且通常仅在无法使用 proper防火墙时使用（通常在共享托管服务等场景下）。
  # 保持此列表为空意味着没有IP地址白名单限制。
  # 支持IP地址、子网和纯文本文件链接。
  #proxy-protocol-whitelisted-ips: [ "127.0.0.1", "172.18.0.0/16", "https://example.com/whitelist.txt" ]

remote:
  # 远程（Java版）服务器的IP地址
  # 若设为“auto”，独立版中远程地址将设为127.0.0.1；
  # 插件版建议保持“auto”，以便Geyser自动配置地址、端口和认证类型。
  # 若安装了floodgate，请保持“auto”。
  address: auto
  # 远程（Java版）服务器的端口
  # 插件版中，若地址设为“auto”，端口将跟随服务器的监听端口。
  port: 25565
  # 认证类型。可选offline（离线）、online（在线）或floodgate（详见https://github.com/GeyserMC/Geyser/wiki/Floodgate）。
  # 插件版建议保持“address”为“auto”，以便自动配置Floodgate支持。
  # 若已安装Floodgate且“address”设为“auto”，则“auth-type”将自动设为floodgate。
  auth-type: online
  # 连接服务器时是否启用PROXY协议。
  # 仅在以下情况使用：
  # 1) 你的服务器支持PROXY协议（通常不支持）
  # 2) 你运行的Velocity或BungeeCord代理在主配置中启用了该选项。
  # 若不了解此项，请勿修改！
  use-proxy-protocol: false
  # 将基岩版客户端用于连接的主机名转发到Java版服务器
  # 用于代理服务器的强制主机名场景。
  forward-hostname: false

# Floodgate使用加密确保来自授权源的访问。
# 此项应指向Floodgate（BungeeCord、Spigot或Velocity版）生成的公钥。
# 不使用Floodgate时可忽略。
# 若在同一服务器上使用插件版Floodgate，将自动获取密钥。
floodgate-key-file: key.pem

# 仅适用于在线模式认证。
# 存储基岩版玩家登录后需保存的Java版账号列表。
# 此功能保存可用于后续认证的令牌，不存储邮箱或密码，
# 但添加列表项及允许他人访问Geyser实例文件时仍需谨慎。
# 从列表中移除名称后，下次启动Geyser时将删除其缓存的登录信息。
# 令牌存储在与本配置文件同目录的“saved-refresh-tokens.json”中。
saved-user-logins:
  - ThisExampleUsernameShouldBeLongEnoughToNeverBeAnXboxUsername
  - ThisOtherExampleUsernameShouldAlsoBeLongEnough

# 指定用户授权Geyser访问其微软账号的等待时间（秒）。
# 此期间内用户可断开服务器连接。
pending-authentication-timeout: 120

# 基岩版客户端首次打开命令提示符时，若收到大量命令可能会冻结。
# 禁用此项可阻止发送命令建议，解决基岩版客户端的冻结问题。
command-suggestions: true

# 以下三个选项启用“ping 穿透”——从Java版服务器获取MOTD、玩家数量和/或协议名称并转发。
# 将远程服务器的MOTD中继给基岩版玩家。
passthrough-motd: true
# 将远程服务器的玩家数量和最大玩家数中继给基岩版玩家。
passthrough-player-counts: true
# 启用LEGACY ping穿透。仅当MOTD或玩家数量显示异常时启用。
# 独立版中此项无效。
legacy-ping-passthrough: false
# 远程服务器的ping间隔时间（秒）。仅适用于独立版或LEGACY ping穿透。
# 若出现BrokenPipe错误，可增大此值。
ping-passthrough-interval: 3

# 是否将玩家延迟转发到服务器。启用可使基岩版玩家的延迟更准确，
# 但可能导致玩家更容易超时。
forward-player-ping: false

# 最大可连接玩家数。目前仅为显示效果，不实际限制玩家数量。
max-players: 100

# 是否在控制台输出调试信息
debug-mode: false

# 允许发送模拟的冷却指示器。基岩版玩家使用1.8 combat机制，默认不显示冷却，
# 启用此项可显示。
# 注意：启用冷却后，部分用户可能在冷却期间看到黑框，如下所示：
# https://cdn.discordapp.com/attachments/613170125696270357/957075682230419466/Screenshot_from_2022-03-25_20-35-08.png
# 可在基岩版设置的辅助功能选项中，将“文本背景透明度”设为0来解决。
# 此项可选“title”“actionbar”或“false”
show-cooldown: title

# 控制是否向玩家显示坐标。
show-coordinates: true

# 是否阻止基岩版玩家使用搭脚手架的方式搭桥。
disable-bedrock-scaffolding: false

# 若设置此项，基岩版玩家使用表情动作时，会切换副手和主手物品，模拟Java版的按键功能。
# 有三个选项：
# disabled - 默认/备用选项，不启用此功能
# no-emotes - 表情动作不会发送给其他基岩版客户端，仅切换副手。实际上禁用了表情的可见性。
# emotes-and-offhand - 表情动作会发送给基岩版客户端，同时切换副手。
emote-offhand-workaround: "disabled"

# 若客户端请求的语言不存在，使用的默认语言。取消注释可更改默认系统语言。
# default-locale: en_us

# 指定图片缓存到磁盘的天数，以减少重复从互联网下载。
# 0为禁用。（默认：0）
cache-images: 0

# 允许显示自定义头颅。在较旧/性能较弱的设备上，启用可能导致性能下降。
allow-custom-skulls: true

# 每个玩家可显示的最大自定义头颅数量。增大此值可能降低弱设备的性能。
# 设为-1将显示所有自定义头颅，不受距离和数量限制。
max-visible-custom-skulls: 128

# 玩家周围显示自定义头颅的半径（方块）。
custom-skull-render-distance: 32

# 是否添加基岩版中原本不存在的物品和方块。
# 仅在使用不支持“传输数据包”式服务器切换的代理时需要禁用。
# 禁用后，熔炉矿车物品将映射为漏斗矿车物品。
# Geyser的方块、物品和头颅映射系统也将禁用。
# 更改此项需重启Geyser生效。
add-non-bedrock-items: true

# 基岩版会阻止在下界Y127以上放置和显示方块。
# 此配置通过将下界维度ID改为末地ID来解决此问题。
# 主要缺点是整个下界将使用相同的红色雾效，而非不同生物群系的不同雾效。
above-bedrock-nether-building: false

# 若存在资源包，强制客户端加载所有资源包。
# 若设为false，用户即使不想下载资源包也能连接服务器。
force-resource-packs: true

# 允许解锁Xbox成就。
xbox-achievements-enabled: false

# 服务器是否记录玩家的IP地址。
log-player-ip-addresses: true

# 当有新版本Geyser支持当前版本不支持的基岩版时，是否向控制台和管理员发送提醒。建议保持启用，因为许多基岩版平台会自动更新。
notify-on-new-bedrock-update: true

# 用于标记基岩版玩家背包中不可用槽位的物品。例如创造模式下的2x2合成格，或非标准尺寸的自定义背包菜单。默认使用屏障方块。
unusable-space-block: minecraft:barrier

# bStats是一个完全匿名的统计跟踪工具，仅记录Geyser的基本信息，如在线人数、使用Geyser的服务器数量、运行系统等。可访问https://bstats.org/了解更多。
# https://bstats.org/plugin/server-implementation/GeyserMC
metrics:
  # 是否启用统计功能
  enabled: true
  # 服务器UUID，请勿修改！
  uuid: generateduuid

# 高级选项——非专业人士请勿修改！

# Geyser会在每个计分板数据包后更新计分板，但每秒处理大量计分板数据包可能导致严重卡顿。
# 此选项指定每秒计分板数据包达到多少时，将计分板更新限制为每秒4次。
scoreboard-packet-threshold: 20

# 允许来自ProxyPass和Waterdog的连接。
# 参考https://www.spigotmc.org/wiki/firewall-guide/获取帮助——使用UDP而非TCP。
enable-proxy-connections: false

# 互联网支持的最大MTU为1492，但可能导致数据包分片问题。
# 默认值为1400。
mtu: 1400

# 是否不创建TCP连接而直接连接到Java版服务器。
# 仅当与数据包或网络交互的插件无法与Geyser正常工作时才禁用。
# 插件版启用此项时，远程地址和端口设置将被忽略。
# 插件版禁用此项可能导致性能下降和延迟增加。
use-direct-connection: true

# Geyser是否尝试为基岩版玩家禁用压缩。由于无需通过网络处理Java版数据包，禁用压缩应有益处。
# 需启用use-direct-connection。
disable-compression: true

config-version: 4

内容由 AI 生成
